### ISSUE TITLE
Add a docker-compose demo

### ISSUE THREAD

**Issue by liuliqiang** [yetship/celerybeatredis#21]

**Comment by isaqueprofeta** [comment]
I can help you with this... let's first merge the bug from #20 ok?

**Comment by liuliqiang** [comment]
Thanks @isaqueprofeta, that's great.
I assigned this issue to you.

**Comment by isaqueprofeta** [comment]
I made two options in branches on my fork:

- First, with pure docker-compose, in that case, I needed to duplicate the full example folder to a new one, because of the 'localhost' settings for the Redis URLs.
  - https://github.com/isaqueprofeta/celerybeatredis/tree/dockercompose-example

- Second, with Docker combined with Supervisord, in that case, is a single container with all the 3 components.
  - https://github.com/isaqueprofeta/celerybeatredis/tree/dockersupervisor-example

You can try them (I also updated the README.md with instructions) and tell me which one do you want me to pull request, personally I find more elegant to use pure docker-compose, even with doubled code from examples.

**Comment by liuliqiang** [comment]
@isaqueprofeta that's great to see your different try.

After reviewed the two way, I prefer the pure docker-compose version，for these reason：

- People will clearly know there are 3 component
- As container practice, it's best to run only one process in one container
- It will also show that our redis beat not only support `localhost`, we have config `CELERY_REDIS_SCHEDULER_URL` to specify redis addr.

I also add some comment in the commit.

**Comment by isaqueprofeta** [comment]
Great to see that we have the same opinion. I also replied to the comments.

**Comment by liuliqiang** [comment]
That's well.
Let's do follow your suggestion, and drop the example by pure local run.
And remind only docker-compose example for users that want to try redisbeat.

**Comment by isaqueprofeta** [comment]
Can you please review this last commit dropping the local example? The most important part I think that is the README.md with the explanations.

**Comment by liuliqiang** [comment]
Just a little comment for me.
Others LGTM.
