### ISSUE TITLE
each time init RedisScheduler  - repeated call 

### ISSUE THREAD

**Issue by heylel** [yetship/celerybeatredis#29]
when I run `celery beat -A manage.celery_app -S RedisScheduler` ，it will init a new RedisScheduler object,and obey this call chain:` __init__`->setup_schedule->merge_inplace. 

In merge_inplace() it will load tasks from conf and redis's original tasks.
while I have a dout when you add/rm a job like this:
```
if __name__ == "__main__":
    schduler = RedisScheduler(app=app)
    schduler.add(**{
        'name': 'sub-perminute',
        'task': 'tasks.sub',
        'schedule': timedelta(seconds=3),
        'args': (1, 1)
    })
```
I wonder whether it will call this chain` __init__`->setup_schedule->merge_inplace again, which means I have to reload all the tasks first??

**Comment by adrienyhuel** [comment]
When you want to add a task from another python app, you have to init a RedisScheduler instance.
But when you do that, it calls init, and steup schedules, merge...

It became a big issue for me.
I use a multithreaded API (built with FastAPI), which init a RedisScheduler instance to manage schedules.
Sometimes, when I restart this API, some or all schedules get deleted from Redis.

I think it's because at each RedisScheduler instance init (in each thread), it reads from Redis, erase all, and insert again in Redis (in merge_inplace method).
But if multiple threads init an instance in parallel, it may enter in a race condition, where one thread read from Redis when another just removed all. Then, this thread remove all too, but has nothing to insert.

Maybe the best would be to have the methods (add, list, get, _remove_db) made static or outside RedisScheduler class.

**Comment by liuliqiang** [comment]
Add a new param `skip_init` to `RedisScheduler`, and if we init the `RedisScheduler` with `skip_init=True`, it will not edit the current tasks, just provide the interface to operate the tasks.
